#!/usr/bin/perl
use strict;
use warnings;
use autodie;
use feature 'say';

use File::Basename qw(dirname);
use File::Spec::Functions qw(catfile);

my $SCRIPT_PATH = dirname $0;
my $jum_jar = (glob "$SCRIPT_PATH/../target/*.jar")[0];
my $package_file = "./jum.toml";

system "$SCRIPT_PATH/run init \"$jum_jar\" --package-version 1.0 --author folgue --description \"Java Utility Manager\" --output $package_file --jdk-version 22 --name jum";
system "java -jar \"$jum_jar\" install $package_file --jar $jum_jar";
